// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dynfjrjzfvgypixflqgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5bmZqcmp6ZnZneXBpeGZscWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODI1MTAsImV4cCI6MjA1ODk1ODUxMH0.WDdcR5KBZiIUEuugg_ai8eWFFUyyLF5pHuRTQx54hHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);